//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Logica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencias
    {
        public int id_asistencia { get; set; }
        public int id_empleado { get; set; }
        public string tipo_asistencia { get; set; }
        public System.DateTime fecha_asistencia { get; set; }
        public string hora_asistencia { get; set; }
        public string ip_conexion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string estado { get; set; }
        public System.DateTime fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mod { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
