//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Logica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_empleado
    {
        public int id_cliemp { get; set; }
        public int id_cliente { get; set; }
        public int id_empleado { get; set; }
        public Nullable<int> id_evaluador { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual evaluadors evaluadors { get; set; }
    }
}
