//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Logica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correlativo
    {
        public int id_correlativo { get; set; }
        public int numero { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string tipo_correlativo { get; set; }
    }
}
