//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Logica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int id_documento { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public string leido_por { get; set; }
    }
}
