//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Logica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class app_control : DbContext
    {
        public app_control()
            : base("name=app_control")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asistencias> asistencias { get; set; }
        public virtual DbSet<cliente_empleado> cliente_empleado { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<correlativo> correlativo { get; set; }
        public virtual DbSet<documentos> documentos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<encuesta_config> encuesta_config { get; set; }
        public virtual DbSet<evaluadors> evaluadors { get; set; }
        public virtual DbSet<gpreguntas> gpreguntas { get; set; }
        public virtual DbSet<preguntas> preguntas { get; set; }
        public virtual DbSet<reporte_asistencia> reporte_asistencia { get; set; }
        public virtual DbSet<resultado> resultado { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<pr_sel_reporte_asistencia_Result> pr_sel_reporte_asistencia(Nullable<int> totalMinutos, Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta)
        {
            var totalMinutosParameter = totalMinutos.HasValue ?
                new ObjectParameter("TotalMinutos", totalMinutos) :
                new ObjectParameter("TotalMinutos", typeof(int));
    
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("FechaDesde", fechaDesde) :
                new ObjectParameter("FechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("FechaHasta", fechaHasta) :
                new ObjectParameter("FechaHasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_sel_reporte_asistencia_Result>("pr_sel_reporte_asistencia", totalMinutosParameter, fechaDesdeParameter, fechaHastaParameter);
        }
    }
}
