//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Logica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultado
    {
        public int id_resultado { get; set; }
        public int id_encuesta { get; set; }
        public int id_evaluador { get; set; }
        public int id_empleado { get; set; }
        public int id_pregunta { get; set; }
        public int anio_evaluacion { get; set; }
        public int mes_evaluacion { get; set; }
        public System.DateTime fecha_evaluacion { get; set; }
        public int puntaje { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mod { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual encuesta_config encuesta_config { get; set; }
        public virtual evaluadors evaluadors { get; set; }
        public virtual preguntas preguntas { get; set; }
    }
}
